---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: martinmuraskovas/martin-node-app
          ports:
            - containerPort: 3000
          env:
          - name: DB_HOST
            value: DB_HOST=mongodb://10.102.30.215:27017/posts